---
version: '2.4'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demopass
      MYSQL_PASSWORD: demopass
      MYSQL_USER: demouser
      MYSQL_DATABASE: demodb
    volumes:
    - db:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: demouser
      WORDPRESS_DB_PASSWORD: demopass
      WORDPRESS_DB_NAME: demodb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
  db: