---
version: '2.4'
services:
  wcg1:
    image: wcg:big
    ports:
    - "8888:8888"
    depends_on:
      wcg2:
        condition: service_healthy
  wcg2:
    image: wcg:big
    ports:
    - "8890:8888"
    healthcheck:
      test: curl -f http://localhost:8888||exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      # start_period: 10s