pipeline {
    agent {
        label '!docker'
    }
    options {
        timestamps()
    }
    stages{
      stage('Test'){
        steps{
          sh ''' echo Hello github
          '''
        }
      }
    }
}
