---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-svc
spec:
  selector:
    app: {{ .Values.container.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}