---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: wp
          image: wordpress
          imagePullPolicy: IfNotPresent
          env:
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: WORDPRESS_DB_HOST
            value: svc-mysql

          ports:
          - containerPort: 80
          volumeMounts:
          - name: wp-data
            mountPath: /var/www/html

      volumes:
      - name: wp-data
        persistentVolumeClaim:
          claimName: pvc-wp
---
apiVersion: v1
kind: Service
metadata:
  name: svc-wp
spec:
  selector:
    app: wp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80